# Generated by Django 5.2.5 on 2025-08-23 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedfile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='question',
            name='tags',
        ),
        migrations.DeleteModel(
            name='QuestionFile',
        ),
        migrations.DeleteModel(
            name='UploadedFile',
        ),
    ]
